org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.249
loader_version_range=[1,)
geckolib_version=4.9.2

mod_id=dark_caverns
mod_name=Dark Caverns
mod_license=All Rights Reserved
mod_version=1.2.1
mod_group_id=com.freeranger.dark_caverns
mod_authors=Freeranger
mod_description=A new dimension hidden deep below the surface...
