modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL=""
license="All rights reserved"
[[mods]]
modId="dark_caverns"
version="1.1"
displayName="Dark Caverns"
logoFile="logo.png"
logoBlur=false
authors="Freeranger"
description='''A new dimension hidden deep below the surface...'''
[[dependencies.dark_caverns]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.42,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dark_caverns]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.16.5]"
    ordering="NONE"
    side="BOTH"
[[dependencies.dark_caverns]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.33,]"
    ordering="NONE"
    side="BOTH"